### ISSUE TITLE
Head screen rendering

### ISSUE THREAD

**Issue by chuigda** [chuigda/Project-WG#3]
Head screen rendering should at least support:
- Pre-programmed animations (stored in configuration files, I prefer)
- Face tracking (needs good design)
- Volume bars

**Comment by chuigda** [comment]
To implement these rendering, I think OpenGL 3.3+ "Render to texture" would be useful. And according to [this post](https://stackoverflow.com/questions/36724013/render-anything-to-texture) rtt is also applicable to fixed-functions pipeline, even immediate mode. I think this would be quite useful.

**Comment by CousinZe** [comment]
Let me help.

**Comment by chuigda** [comment]
Another choice is to render screen content from CPU side (maybe with `QPainter` or OpenCV) and then upload the content as texture. This would be (in theory) slower, but would allow us performing much more interesting effects (though maybe not hardware accelerated).

**Comment by chuigda** [comment]
[NeHe's tutorial](http://nehe.gamedev.net/tutorial/radial_blur__rendering_to_a_texture/18004/) could be very valuable under such circumstance. Also, FBO is not indeed necessary to RTT according to this tutorial (though this would pollute the default, window system provided framebuffer and thus nasty).

**Comment by chuigda** [comment]
> FBO is not indeed necessary to RTT according to this tutorial (though this would pollute the default, window system provided framebuffer and thus nasty).

FBO rendering also involves changing global states like viewports or so. Let's just focus on simplicity or performance.

**Comment by chuigda** [comment]
Perfect.

**Comment by chuigda** [comment]
> Also, FBO is not indeed necessary to RTT according to this tutorial

After experimenting and confirmed with CrLF0710, this piece of code may be out-dated or not portable. It's better to stick to the FBO way.
