### ISSUE TITLE
面部捕捉

### ISSUE THREAD

**Issue by chuigda** [chuigda/Project-WG#4]
找了一些可以用来参考的 repository
- https://github.com/by-sabbir/HeadPoseEstimation
- https://github.com/lincolnhard/head-pose-estimation

此外可以考虑下是不是不用 `solvePNP` 也能完成任务

**Comment by chuigda** [comment]
VTS看起来有个不错的API可以用，🇰🇷了

https://github.com/DenchiSoft/VTubeStudio#requesting-list-of-available-tracking-parameters

**Comment by CousinZe** [comment]
VTS's face capture is based on [OpenSeeFace](https://github.com/emilianavt/OpenSeeFace/releases/tag/v1.20.4). Maybe we can directly utilize OSF, bypassing the VTS's rendering. And after that, we won't need to include any proprietary software in our release.

**Comment by chuigda** [comment]
OSF requires a little complex setup, and comes without some utilities (meaning that we have to implement our own calibration things or so). Let's just stick to VTS by this time.

**Comment by chuigda** [comment]
Well done @CousinZe
